apiVersion: v1
kind: List
metadata:
  name: DemoApp
  namespace: default
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: demo-app
    namespace: default
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: demo-app
        app.kubernetes.io/instance: demo-app
    replicas: 1
    template:
      metadata:
        labels:
          app.kubernetes.io/name: demo-app
          app.kubernetes.io/instance: demo-app
      spec:
        containers:
          - name: nginx
            image: nginx:mainline-alpine
            ports:
            - containerPort: 80
              name: http
- apiVersion: v1
  kind: Service
  metadata:
    name: demo-app
    namespace: default
    annotations:
      service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: private
  spec:
    ports:
      - name: http
        port: 80
        targetPort: http
    selector:
      app.kubernetes.io/name: demo-app
      app.kubernetes.io/instance: demo-app
    type: LoadBalancer
